// #define NO_AUTO_SHIFT_SPECIAL
// #define  NO_AUTO_SHIFT_NUMERIC
#define RGBLIGHT_SPLIT
#define RGBLIGHT_SLEEP
#define SPLIT_LAYER_STATE_ENABLE

#undef  MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0
#undef  MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA 4
#undef  MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef  MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 5
#undef  MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 60

// 8
// 10
// 30
